#ifndef UBOATCVSLIBRARY_GLOBAL_H
#define UBOATCVSLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UBOATCVSLIBRARY_LIBRARY)
#define UBOATCVSLIBRARY_EXPORT Q_DECL_EXPORT
#else
#define UBOATCVSLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // UBOATCVSLIBRARY_GLOBAL_H
